### ISSUE TITLE
Add that a Verify NuGet package is needed.

### ISSUE THREAD

**Issue by glennawatson** [VerifyTests/Verify.SourceGenerators#15]
#### Describe the bug

The documentation mentioned the `Verify.SourceGenerators` is required, but possibly mention that a unit testing framework adapter is required as well such as `Verify.Xunit` in the documentation as well.

#### Minimal Repro

Just a documentation change.

#### Submit a PR that fixes the bug

https://github.com/VerifyTests/Verify.SourceGenerators/pull/16

**Comment by SimonCropp** [comment]
thanks for the PR
