### ISSUE TITLE
Locations differ between Windows and Unix based systems

### ISSUE THREAD

**Issue by koenbeuk** [VerifyTests/Verify.SourceGenerators#2]
The output of the added #1 test differs from a Unix based environment to Windows. This is also causing tests related to [this](https://github.com/koenbeuk/EntityFrameworkCore.Projections/pull/1) PR to fail.

**Comment by koenbeuk** [comment]
Perhaps we should add a ValueConverter that takes a Location and prints it out in terms of its LineNumber/Offset rather than Offset within the source text. Let me know if you like my help with this.

**Comment by SimonCropp** [comment]
i merged your PR, and also enabled tests on macos and linux. and u r correct it fails

> prints it out in terms of its LineNumber/Offset rather than Offset within the source text. 

not sure i understand this?

> Let me know if you like my help with this.

yes help would be greatly appreciated
