### ISSUE TITLE
Diagnostic paths are not normalized across platforms

### ISSUE THREAD

**Issue by RReverser** [VerifyTests/Verify.SourceGenerators#286]
#### Preamble

I'm using the following package versions:

```xml
<PackageReference Include="Verify.SourceGenerators" Version="2.2.0" />
<PackageReference Include="Verify.XUnit" Version="25.0.1" />
```

#### Describe the bug

When testing snapshots of emitted diagnostics, the slashes used in paths are not normalized, leading to failures when compared across different platforms.

Example snapshot generated and stored on Windows:

```json5
...
{
  Id: BSATN0002,
  Title: [SpacetimeDB.Type] enums cannot have explicit values,
  Severity: Error,
  WarningLevel: 0,
  Location: {ProjectDirectory}fixtures\diag\Lib.cs: (11,17)-(11,20),
  MessageFormat: {0}.{1} has an explicit value {2} which is not allowed in SpacetimeDB enums.,
  Message: TestEnumWithExplicitValues.EnumVariant1 has an explicit value 1 which is not allowed in SpacetimeDB enums.,
  Category: SpacetimeDB.BSATN
},
...
```

fails on Linux-based CI, where the same diagnostic is generated as:

```json5
...
{
  Id: BSATN0002,
  Title: [SpacetimeDB.Type] enums cannot have explicit values,
  Severity: Error,
  WarningLevel: 0,
  Location: {ProjectDirectory}fixtures/diag/Lib.cs: (11,17)-(11,20),
  MessageFormat: {0}.{1} has an explicit value {2} which is not allowed in SpacetimeDB enums.,
  Message: TestEnumWithExplicitValues.EnumVariant1 has an explicit value 1 which is not allowed in SpacetimeDB enums.,
  Category: SpacetimeDB.BSATN
},
...
```

Note the difference in `\` vs `/` in the `Location` field.

I'd expect those to be normalized just like the project directory, before being written out.

#### Minimal Repro

I don't have one handy - the project this is from is somewhat complicated and uses `MSBuildWorkspace` - but any diagnostic with location filename set to a Windows-like path should work.

#### Submit a PR that fixes the bug

Submit a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/) that fixes the bug. Include in this PR a test that verifies the fix. If you were not able to fix the bug, a PR that illustrates your partial progress will suffice.

**Comment by SimonCropp** [comment]
can u try 2.4.1

**Comment by RReverser** [comment]
Perfect, thanks! In my workaround I normalized path separators to `/` meanwhile, so was a bit surprised to see snapshots failing as they now expect `\`, but at least it's now consistent between platforms.

Side-note: after upgrading Verify.SourceGenerators, I started getting

```
  Error Message:
   System.TypeLoadException : Could not load type 'Guard' from assembly 'Verify, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c7a34512ecd69090'.
  Stack Trace:
     at VerifyXunit.Verifier.Verify(VerifySettings settings, String sourceFile, Func`2 verify, Boolean useUniqueDirectory)
   at VerifyXunit.Verifier.Verify(Object target, VerifySettings settings, String sourceFile) in /_/src/Verify.Xunit/Verifier_Object.cs:line 44    
```

Then I updated Verify itself, got

```
error NU1107: Version conflict detected for xunit.extensibility.core. 
Install/reference xunit.extensibility.core 2.9.0 directly to project [...] to resolve this issue.
```

Then I updated Xunit too, and everything worked. I'm surprised this had to fail that "late" in the pipeline though with rather obscure errors. Perhaps `Verify` should have a different `AssemblyVersion` per major release, as per usual guidelines, so that loading `Verify.SourceGenerators` would fail with clear version mismatch when user has an incompatible version of `Verify`?

**Comment by RReverser** [comment]
Actually... I have to reopen. There is a new issue: now that paths don't use native slash delimiters, `Verify` scrubber doesn't catch them and CI snapshots look like

```
      Location: \home\runner\work\SpacetimeDB\SpacetimeDB\crates\bindings-csharp\Codegen.Tests\fixtures\diag\Lib.cs: (16,17)-(16,20),
      ...
```

instead of

```
      Location: {ProjectDirectory}fixtures\diag\Lib.cs: (16,17)-(16,20),
```

I suppose `Verify` itself will have to be changed to account for both?

**Comment by SimonCropp** [comment]
can u try Verify 26.4.5

**Comment by RReverser** [comment]
Thanks, works as expected now.

**Comment by jvandertil** [comment]
It seems there is still an issue here...

On Windows I get 'normalized' path such as:
{ProjectDirectory}Tools/REDACTED.PROJECT.NAME/SourceGenTests.cs

However, on Linux (build agent) for some reason the path separator reported is `\`:
{ProjectDirectory}Tools\REDACTED.PROJECT.NAME\SourceGenTests.cs

And obviously the test fails.

Versions used:
Verify.MsTest 27.1.0
Verify.SourceGenerators: 2.5.0

**Comment by SimonCropp** [comment]
@jvandertil can u share a failing test as a pull request
