### ISSUE TITLE
Ignoring source text

### ISSUE THREAD

**Issue by virzak** [VerifyTests/Verify.SourceGenerators#67]
How do I ignore a specific source text?

My source generator outputs an attribute every time. Most of the tests are about things other than attribute.
Tried using `verifier.IgnoreInstance` with a delegate, but it didn't seem to fire.

I'm guessing this should be a common problem for people and perhaps be added to the documentation?

**Comment by SimonCropp** [comment]
hows this https://github.com/VerifyTests/Verify.SourceGenerators#manipulating-source  ?

**Comment by SimonCropp** [comment]
can you share a failing test as a pull request to show your scenario

**Comment by virzak** [comment]
Here is the source generator: https://github.com/zompinc/sync-method-generator

The snapshot directory contains multiple versions of file \<TestCase>CreateSyncVersionAttribute.g.verified.cs - [example](https://github.com/zompinc/sync-method-generator/blob/d37aebee0ecac0bdd7c9940b49bf7fa6370c1dcd/tests/Zomp.SyncMethodGenerator.Tests/Snapshots/GenericMathTests.GeneratesWithIProgressCorrectly.DotNet6_0%23CreateSyncVersionAttribute.g.verified.cs)

\<TestCase>CreateSyncVersionAttribute.g.verified.cs take up half of the directory and are of no value in all but one test case.

The verifier is set [here](https://github.com/zompinc/sync-method-generator/blob/d37aebee0ecac0bdd7c9940b49bf7fa6370c1dcd/tests/Zomp.SyncMethodGenerator.Tests/TestHelper.cs#L56-L63)

**Comment by s-tarasov** [comment]
Is there a solution to this problem?

**Comment by wdkr** [comment]
I'm using the following workaround. If there's a better solution I'd be interested to know.

```C#
public sealed class RunResultWithIgnoreList
{
    public required GeneratorDriverRunResult Result { get; init; }
    public List<string> IgnoredFiles { get; init; } = new();
}
```

```C#
public static class ModuleInitializer
{
    [ModuleInitializer]
    public static void Init()
    {
        VerifySourceGenerators.Initialize();
        VerifierSettings.RegisterFileConverter<RunResultWithIgnoreList>(Convert);
    }

    private static ConversionResult Convert(RunResultWithIgnoreList target, IReadOnlyDictionary<string, object> context)
    {
        var exceptions = new List<Exception>();
        var targets = new List<Target>();
        foreach (var result in target.Result.Results)
        {
            if (result.Exception != null)
            {
                exceptions.Add(result.Exception);
            }

            var collection = result.GeneratedSources
                .OrderBy(x => x.HintName)
                .Where(x => !target.IgnoredFiles.Contains(x.HintName))
                .Select(SourceToTarget);
            targets.AddRange(collection);
        }

        if (exceptions.Count == 1)
        {
            throw exceptions.First();
        }

        if (exceptions.Count > 1)
        {
            throw new AggregateException(exceptions);
        }

        if (target.Result.Diagnostics.Any())
        {
            var info = new
            {
                target.Result.Diagnostics
            };
            return new(info, targets);
        }

        return new(null, targets);
    }

    private static Target SourceToTarget(GeneratedSourceResult source)
    {
        var data = $"""
            //HintName: {source.HintName}
            {source.SourceText}
            """;
        return new("cs", data, Path.GetFileNameWithoutExtension(source.HintName));
    }
}
```

And at the point of verification

```C#
var target = new RunResultWithIgnoreList
{
    Result = driver.GetRunResult(),
    IgnoredFiles = { "SomeAttribute.g.cs", "SomeOtherSource.g.cs" }
};

return Verifier.Verify(target).UseDirectory("Snapshots");
```

**Comment by SimonCropp** [comment]
again. if someone can submit a failing unit test, i can have a look at fixing this

**Comment by morcam** [comment]
@wdkr Thanks! That was very helpful!

@SimonCropp Maybe there's some misunderstanding here I can help clear up? From my understanding, this isn't really a bug in the code. The issue is really that it's a missing feature that can be rather problematic. Many source generators always output a particular source file - in the original poster's comment it was an attribute definition, and in my case it's a generated-per-assembly class. 

Regardless, the source generator being tested outputs both some partial classes and this static generated file. This means that every single test case now has at least two files - the actual partial class that's being generated for the test case, and the static generated file which (nearly) never changes. This requires you to review the static generated file (which is not intended to be under test in these unit test cases) for every new test case. And if you change the static generated file at all, then every single test case in the project fails and needs to be accepted again. 

It's preferable to just "ignore" this static generated file in every test case except for perhaps one test case that's specifically looking for it. Which is what wdkr's code allows you to do.

**Comment by SimonCropp** [comment]
> The issue is really that it's a missing feature that can be rather problematic

happy to consider a PR that adds this feature

**Comment by virzak** [comment]
This is related.

After dropping the attribute(s), the test includes a single source. That source includes `using` directives, namespaces, classes, method bodies, etc. About 5% of my test need the entire source, 45% need the class body and 50% only need the method contents.

I expanded on @wdkr's solution to trim accordingly and remove indentation:

Every test can pass an [enum](https://github.com/zompinc/sync-method-generator/blob/c44fe5ed7eec4dc6386451993e83abccb07da611/tests/Generator.Tests/SourceType.cs) of what to store:

```cs
public enum SourceType
{
    /// <summary>
    /// Listing of a body of a block method.
    /// </summary>
    MethodBody,

    /// <summary>
    /// Listing of a body of a class.
    /// </summary>
    ClassBody,

    /// <summary>
    /// Listing for the file in full.
    /// </summary>
    Full,
}
```

If `MethodBody` or `ClassBody` are selected, default method+class or class declarations are added respectively. Indentation of 8 or 4 spaces is added as well.

The `ModuleInitializer` [class](https://github.com/zompinc/sync-method-generator/blob/c44fe5ed7eec4dc6386451993e83abccb07da611/tests/Generator.Tests/ModuleInitializer.cs) copied from the above example runs a regex on the incoming source to determine if the class+method or class is default and if so strips it and removes indentation.

The result is that the test methods are extremely [small](https://github.com/zompinc/sync-method-generator/blob/c44fe5ed7eec4dc6386451993e83abccb07da611/tests/Generator.Tests/DelegateTests.cs#L63-L68).

```cs
    [Fact]
    public Task AsyncDelegateExplicit() => """
Func<System.Threading.Tasks.Task> delAsync = async () => await Task.CompletedTask;
await delAsync();
""".Verify(sourceType: SourceType.MethodBody);
}
```

Verified sources are even [smaller](https://github.com/zompinc/sync-method-generator/blob/c44fe5ed7eec4dc6386451993e83abccb07da611/tests/Generator.Tests/Snapshots/DelegateTests.AsyncDelegateExplicit%23g.verified.cs):

```cs
﻿//HintName: Test.Class.MethodAsync.g.cs
global::System.Action del = () => { };
del();
```

**Comment by TimothyMakkison** [comment]
I've added this feature in #267 thanks to Simon.

```C#
Verify(driver).IgnoreGeneratedResult(
            _ => _.HintName.Contains("helper"));
```

More details in the [readme](https://github.com/VerifyTests/Verify.SourceGenerators?tab=readme-ov-file#snippet-IgnoreFile).
